import apiService from './apiService';

class PaymentService {
  constructor() {
    // Use API service directly, no need for separate base URL
    this.apiService = apiService;
  }

  /**
   * Generate voucher code
   */
  generateVoucherCode() {
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1000);
    return `VCH${timestamp}${random}`;
  }

  /**
   * Validate payment data
   */
  validatePaymentData(paymentData) {
    const errors = [];

    if (!paymentData.customerName || paymentData.customerName.trim() === '') {
      errors.push('Customer name is required');
    }

    if (!paymentData.phoneNumber || paymentData.phoneNumber.trim() === '') {
      errors.push('Phone number is required');
    }

    // Location is optional - removed requirement
    // if (!paymentData.location || paymentData.location.trim() === '') {
    //   errors.push('Location is required');
    // }

    if (!paymentData.packageId) {
      errors.push('Package selection is required');
    }

    if (!paymentData.amount || paymentData.amount <= 0) {
      errors.push('Valid amount is required');
    }

    return {
      isValid: errors.length === 0,
      errors
    };
  }

  /**
   * Initiate ZenoPay payment
   */
  async initiateZenoPayPayment(paymentData) {
    try {
      const validation = this.validatePaymentData(paymentData);
      if (!validation.isValid) {
        throw new Error(`Validation failed: ${validation.errors.join(', ')}`);
      }

      const formattedPaymentData = {
        customerName: paymentData.customerName.trim(),
        phoneNumber: paymentData.phoneNumber.trim(),
        // Location is optional - removed from required fields
        // location: paymentData.location ? paymentData.location.trim() : undefined,
        packageId: paymentData.packageId,
        packageName: paymentData.packageName,
        amount: paymentData.amount,
        currency: paymentData.currency || 'TZS',
        paymentMethod: 'ZENOPAY'
        // Voucher code is generated by backend, not frontend
        // voucherCode: this.generateVoucherCode()
      };

      console.log('🚀 Initiating ZenoPay Payment:', formattedPaymentData);

      const response = await apiService.initiatePayment(formattedPaymentData);
      
      console.log('🔍 Payment API Response:', response);
      console.log('🔍 Response Status:', response.status);
      console.log('🔍 Response Type:', typeof response.status);
      
      if (response.status === 'success') {
        return {
          status: 'success',
          order_id: response.order_id,
          voucher_code: response.voucher_code,
          message: response.message,
          zenopay_response: response.zenopay_response
        };
      } else {
        throw new Error(response.message || 'Payment initiation failed');
      }
    } catch (error) {
      console.error('❌ ZenoPay Payment Error:', error);
      throw error;
    }
  }

  /**
   * Check payment status
   */
  async checkPaymentStatus(orderId) {
    try {
      console.log(`🔍 Checking payment status for order: ${orderId}`);
      const response = await apiService.checkPaymentStatus(orderId);
      console.log(`🔍 Payment status response:`, response);
      return response;
    } catch (error) {
      console.error(`❌ Error checking payment status: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get user-friendly message for payment status
   */
  getStatusMessage(status) {
    const statusMessages = {
      'PENDING': 'Payment is still being processed. Please complete the payment on your phone.',
      'PROCESSING': 'Payment is being processed. Please wait...',
      'COMPLETED': 'Payment completed successfully! Your voucher code has been generated.',
      'SUCCESS': 'Payment completed successfully! Your voucher code has been generated.',
      'FAILED': 'Payment failed. Please check your mobile money balance and try again.',
      'CANCELLED': 'Payment was cancelled. Please try again.',
      'INSUFFICIENT_BALANCE': 'Insufficient balance in your mobile money account. Please top up and try again.',
      'INVALID_PIN': 'Invalid PIN entered. Please try again with the correct PIN.',
      'USER_CANCELLED': 'Payment was cancelled by user. Please try again.',
      'EXPIRED': 'Payment has expired. Please initiate a new payment.',
      'TIMEOUT': 'Payment timed out. Please try again.',
      'NETWORK_ERROR': 'Network error occurred. Please try again.',
      'ERROR': 'An error occurred during payment. Please try again.'
    };
    return statusMessages[status] || `Payment status: ${status}`;
  }

  /**
   * Poll payment status with enhanced tracking
   */
  async pollPaymentStatus(orderId, onStatusUpdate, maxAttempts = 90, interval = 2000) {
    console.log(`🔄 Starting payment status polling for order: ${orderId}`);
    console.log(`   Max attempts: ${maxAttempts}, Interval: ${interval}ms`);
    
    // Prevent multiple polling instances for the same order
    if (this.activePolling && this.activePolling.has(orderId)) {
      console.log(`⚠️ Polling already active for order: ${orderId}`);
      return () => {
        console.log(`🛑 Ignoring duplicate polling stop for order: ${orderId}`);
      };
    }
    
    // Track active polling
    if (!this.activePolling) {
      this.activePolling = new Set();
    }
    this.activePolling.add(orderId);
    
    const startTime = Date.now();
    let attempts = 0;
    
    // Immediate first poll (don't wait for interval)
    const performPoll = async () => {
      attempts++;
      const elapsedSeconds = Math.floor((Date.now() - startTime) / 1000);
      console.log(`🔄 Polling attempt ${attempts}/${maxAttempts} (${elapsedSeconds}s elapsed) for order: ${orderId}`);
      
      try {
        const result = await this.checkPaymentStatus(orderId);
        
        // Handle response - check both result.data and result directly
        const responseData = result.data || result;
        
        // Check if response has status field
        const responseStatus = responseData.status || 'success';
        const paymentStatus = (responseData.payment_status || responseData.paymentStatus || 'PENDING').toUpperCase();
        
        console.log(`📊 Payment status update: ${paymentStatus} (attempt ${attempts}, ${elapsedSeconds}s elapsed)`);
        console.log(`📊 Full response data:`, responseData);
        
        // Call the status update callback with elapsed time
        if (onStatusUpdate) {
          onStatusUpdate({
            status: paymentStatus,
            message: responseData.message || this.getStatusMessage(paymentStatus),
            orderId: responseData.order_id || responseData.orderId || orderId,
            voucherCode: responseData.voucher_code || responseData.voucherCode,
            voucherGenerated: responseData.voucher_generated || responseData.voucherGenerated || false,
            timestamp: responseData.timestamp || new Date().toISOString(),
            zenopayResponse: responseData.zenopay_response || responseData.zenopayResponse,
            failureReason: responseData.failure_reason || responseData.failureReason,
            elapsedSeconds: elapsedSeconds,
            attempt: attempts
          });
        }
        
        // Stop polling if payment is in final state
        const finalStatuses = ['COMPLETED', 'SUCCESS', 'SUCCESSFUL', 'FAILED', 'CANCELLED', 'EXPIRED', 
                               'TIMEOUT', 'INSUFFICIENT_BALANCE', 'INVALID_PIN', 
                               'USER_CANCELLED', 'NETWORK_ERROR', 'ERROR'];
        if (finalStatuses.includes(paymentStatus)) {
          console.log(`✅ Payment polling completed with status: ${paymentStatus} after ${elapsedSeconds}s`);
          clearInterval(pollInterval);
          this.activePolling.delete(orderId);
          return;
        }
        
        // Also handle case where response status is error but payment_status might be in response
        if (responseStatus === 'error' && !paymentStatus) {
          console.log(`⚠️ Response indicates error but no payment_status found`);
          // Continue polling - might be temporary error
        }
        
        // Stop polling if max attempts reached
        if (attempts >= maxAttempts) {
          console.log(`⏰ Payment polling timeout after ${maxAttempts} attempts (${elapsedSeconds}s)`);
          clearInterval(pollInterval);
          this.activePolling.delete(orderId);
          if (onStatusUpdate) {
            onStatusUpdate({
              status: 'TIMEOUT',
              message: 'Payment status check timed out. Please check your payment manually.',
              orderId: orderId,
              elapsedSeconds: elapsedSeconds,
              attempt: attempts
            });
          }
          return;
        }
        
      } catch (error) {
        const elapsedSeconds = Math.floor((Date.now() - startTime) / 1000);
        console.error(`❌ Error polling payment status (attempt ${attempts}/${maxAttempts}):`, {
          error: error.message,
          orderId,
          elapsedSeconds,
          errorType: error.name,
          errorStack: error.stack
        });
        
        // Provide user-friendly error messages based on error type
        let errorMessage = 'Failed to check payment status. Please try again.';
        if (error.message.includes('CORS') || error.message.includes('blocked')) {
          errorMessage = 'Connection blocked. Please check your network or contact support.';
        } else if (error.message.includes('Network') || error.message.includes('fetch')) {
          errorMessage = 'Network error. Please check your internet connection.';
        } else if (error.message.includes('timeout')) {
          errorMessage = 'Request timed out. Please try again.';
        }
        
        if (attempts >= maxAttempts) {
          console.log(`⏰ Payment polling failed after ${maxAttempts} attempts (${elapsedSeconds}s)`);
          clearInterval(pollInterval);
          this.activePolling.delete(orderId);
          if (onStatusUpdate) {
            onStatusUpdate({
              status: 'ERROR',
              message: errorMessage,
              orderId: orderId,
              elapsedSeconds: elapsedSeconds,
              attempt: attempts,
              error: error.message
            });
          }
          return;
        }
        
        // Continue polling on error (will retry)
        console.log(`🔄 Retrying payment status check (attempt ${attempts + 1}/${maxAttempts})...`);
      }
    };
    
    // Perform immediate first poll
    performPoll();
    
    // Then poll at regular intervals
    const pollInterval = setInterval(performPoll, interval);
    
    // Return a function to stop polling
    return () => {
      console.log(`🛑 Stopping payment polling for order: ${orderId}`);
      console.log(`🛑 Active polling before stop:`, this.activePolling);
      clearInterval(pollInterval);
      this.activePolling.delete(orderId);
      console.log(`🛑 Active polling after stop:`, this.activePolling);
    };
  }

  /**
   * Process complete payment flow
   */
  async processPayment(paymentData) {
    try {
      // Step 1: Initiate payment
      const paymentResult = await this.initiateZenoPayPayment(paymentData);
      
      if (paymentResult.status === 'success') {
        // Step 2: Poll for payment completion
        const statusResult = await this.pollPaymentStatus(paymentResult.order_id);
        
        return {
          ...paymentResult,
          final_status: statusResult.status,
          payment_status: statusResult.payment_status,
          final_message: statusResult.message
        };
      } else {
        throw new Error(paymentResult.message);
      }
    } catch (error) {
      console.error('❌ Payment Process Error:', error);
      throw error;
    }
  }
}

const paymentService = new PaymentService();

export default paymentService;