name = "ggwifi-customer-portal"
compatibility_date = "2024-01-01"

pages_build_output_dir = "Frontend/admin_portal/dist"

[[env.production.routes]]
pattern = "portal.ggwifi.co.tz/*"
zone_name = "ggwifi.co.tz"

[env.production.vars]
VITE_API_URL = "https://api.ggwifi.co.tz/api/v1"
VITE_API_BASE_URL = "https://api.ggwifi.co.tz/api/v1"
