name = "ggwifi-customer-portal"
compatibility_date = "2024-01-01"

[[env.production.routes]]
pattern = "portal.ggwifi.co.tz/*"
zone_name = "ggwifi.co.tz"

[env.production.vars]
VITE_API_URL = "https://api.ggwifi.co.tz/api/v1"
