server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: ggnetworks-backend
  
  profiles:
    active: production
    
  datasource:
    url: jdbc:mysql://localhost:3306/ggnetworks?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:ggnetworks}
    password: ${DB_PASSWORD:secure_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

logging:
  level:
    com.ggnetworks: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ggnetworks-backend.log
    max-size: 10MB
    max-history: 30

# ZenoPay Configuration
zenopay:
  api-url: ${ZENOPAY_API_URL:https://api.zenopay.com}
  api-key: ${ZENOPAY_API_KEY:your_api_key}
  webhook-url: ${ZENOPAY_WEBHOOK_URL:http://your-vps-ip:8080/api/customer-portal/webhook}
  
# SMS Configuration
sms:
  api-url: ${SMS_API_URL:https://api.nextsms.co.tz}
  api-key: ${SMS_API_KEY:your_sms_api_key}
  sender-id: ${SMS_SENDER_ID:GGNETWORKS}
  
# FreeRADIUS Configuration
freeradius:
  host: ${FREERADIUS_HOST:localhost}
  port: ${FREERADIUS_PORT:1812}
  secret: ${FREERADIUS_SECRET:testing123}
  
# MikroTik Configuration
mikrotik:
  default-host: ${MIKROTIK_HOST:192.168.1.1}
  default-port: ${MIKROTIK_PORT:8728}
  default-username: ${MIKROTIK_USERNAME:admin}
  default-password: ${MIKROTIK_PASSWORD:admin}
  
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
