-- Create admin management tables for GGNetworks backend
-- This migration creates all additional tables for comprehensive admin management

-- Routers table
CREATE TABLE routers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL UNIQUE,
    mac_address VARCHAR(17),
    model VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) UNIQUE,
    status ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OFFLINE', 'ERROR') NOT NULL DEFAULT 'ACTIVE',
    type ENUM('MIKROTIK', 'CISCO', 'TP_LINK', 'D_LINK', 'OTHER') NOT NULL,
    location VARCHAR(255) NOT NULL,
    description TEXT,
    firmware_version VARCHAR(100),
    last_maintenance TIMESTAMP NULL,
    next_maintenance TIMESTAMP NULL,
    uptime_seconds BIGINT,
    cpu_usage_percent DOUBLE,
    memory_usage_percent DOUBLE,
    temperature_celsius DOUBLE,
    bandwidth_usage_mbps DOUBLE,
    active_connections INT,
    configuration_json JSON,
    port INT DEFAULT 443,
    username VARCHAR(255),
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_ip_address (ip_address),
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_location (location)
);

-- Static IPs table
CREATE TABLE static_ips (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL UNIQUE,
    user_id BIGINT NULL,
    router_id BIGINT NULL,
    status ENUM('AVAILABLE', 'ASSIGNED', 'RESERVED', 'EXPIRED', 'BLOCKED') NOT NULL DEFAULT 'AVAILABLE',
    type ENUM('PUBLIC', 'PRIVATE', 'BUSINESS', 'PREMIUM') NOT NULL,
    subnet_mask VARCHAR(45) NOT NULL,
    gateway VARCHAR(45),
    dns_primary VARCHAR(45),
    dns_secondary VARCHAR(45),
    monthly_fee DECIMAL(10,2),
    assigned_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    description TEXT,
    mac_address VARCHAR(17),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (router_id) REFERENCES routers(id),
    INDEX idx_ip_address (ip_address),
    INDEX idx_status (status),
    INDEX idx_user_id (user_id)
);

-- Locations table
CREATE TABLE locations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    address TEXT,
    city VARCHAR(255),
    region VARCHAR(255),
    country VARCHAR(255) NOT NULL DEFAULT 'Tanzania',
    postal_code VARCHAR(20),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    status ENUM('ACTIVE', 'INACTIVE', 'PLANNED', 'UNDER_DEVELOPMENT', 'MAINTENANCE') NOT NULL DEFAULT 'ACTIVE',
    type ENUM('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'RURAL', 'URBAN', 'SUBURBAN') NOT NULL,
    coverage_radius_km DOUBLE,
    population_density VARCHAR(100),
    infrastructure_quality VARCHAR(100),
    installation_cost_multiplier DECIMAL(5,2) DEFAULT 1.00,
    is_hotspot_available BOOLEAN DEFAULT TRUE,
    is_pppoe_available BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_name (name),
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_city (city)
);

-- Finance table
CREATE TABLE finances (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(15,2) NOT NULL,
    type ENUM('INCOME', 'EXPENSE', 'REFUND', 'ADJUSTMENT', 'TRANSFER') NOT NULL,
    category ENUM('HOTSPOT_SALES', 'PPPOE_SUBSCRIPTIONS', 'INSTALLATION_FEES', 'STATIC_IP_FEES', 'EQUIPMENT_SALES', 'CONSULTATION_FEES', 'MAINTENANCE_FEES', 'EQUIPMENT_PURCHASE', 'INFRASTRUCTURE_MAINTENANCE', 'STAFF_SALARIES', 'UTILITIES', 'RENT', 'INSURANCE', 'MARKETING', 'SOFTWARE_LICENSES', 'INTERNET_BANDWIDTH', 'TECHNICAL_SUPPORT', 'ADMINISTRATIVE') NOT NULL,
    description TEXT,
    reference_number VARCHAR(100) UNIQUE,
    user_id BIGINT NULL,
    payment_id BIGINT NULL,
    transaction_date TIMESTAMP NOT NULL,
    status ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'DISPUTED') NOT NULL DEFAULT 'COMPLETED',
    tax_amount DECIMAL(10,2),
    discount_amount DECIMAL(10,2),
    net_amount DECIMAL(15,2),
    payment_method VARCHAR(100),
    invoice_number VARCHAR(100),
    receipt_number VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (payment_id) REFERENCES payments(id),
    INDEX idx_type (type),
    INDEX idx_category (category),
    INDEX idx_status (status),
    INDEX idx_transaction_date (transaction_date)
);

-- SMS Campaigns table
CREATE TABLE sms_campaigns (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    message_content TEXT NOT NULL,
    status ENUM('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED') NOT NULL DEFAULT 'DRAFT',
    type ENUM('PROMOTIONAL', 'TRANSACTIONAL', 'NOTIFICATION', 'SURVEY', 'REMINDER', 'WELCOME') NOT NULL,
    target_audience ENUM('ALL_CUSTOMERS', 'HOTSPOT_USERS', 'PPPOE_USERS', 'NEW_CUSTOMERS', 'OLD_CUSTOMERS', 'INACTIVE_CUSTOMERS', 'PREMIUM_CUSTOMERS', 'LOCATION_BASED', 'CUSTOM_LIST') NOT NULL,
    scheduled_at TIMESTAMP NULL,
    sent_at TIMESTAMP NULL,
    total_recipients INT DEFAULT 0,
    sent_count INT DEFAULT 0,
    delivered_count INT DEFAULT 0,
    failed_count INT DEFAULT 0,
    opened_count INT DEFAULT 0,
    clicked_count INT DEFAULT 0,
    cost_per_sms DECIMAL(10,4),
    total_cost DECIMAL(10,2),
    sender_id VARCHAR(50),
    template_id VARCHAR(100),
    notes TEXT,
    is_urgent BOOLEAN DEFAULT FALSE,
    retry_count INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_target_audience (target_audience),
    INDEX idx_scheduled_at (scheduled_at)
);

-- SMS Messages table
CREATE TABLE sms_messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(15) NOT NULL,
    message_content TEXT NOT NULL,
    user_id BIGINT NULL,
    campaign_id BIGINT NULL,
    status ENUM('PENDING', 'SENDING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
    type ENUM('PROMOTIONAL', 'TRANSACTIONAL', 'NOTIFICATION', 'OTP', 'REMINDER', 'WELCOME', 'SURVEY') NOT NULL,
    message_id VARCHAR(100),
    scheduled_at TIMESTAMP NULL,
    sent_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    read_at TIMESTAMP NULL,
    delivery_status VARCHAR(100),
    error_message TEXT,
    retry_count INT DEFAULT 0,
    cost DECIMAL(10,4),
    sender_id VARCHAR(50),
    template_id VARCHAR(100),
    is_urgent BOOLEAN DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (campaign_id) REFERENCES sms_campaigns(id),
    INDEX idx_phone_number (phone_number),
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_campaign_id (campaign_id)
);

-- Loyalty Programs table
CREATE TABLE loyalty_programs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type ENUM('POINTS_BASED', 'TIER_BASED', 'CASHBACK', 'DISCOUNT_BASED', 'GAMIFICATION') NOT NULL,
    target_service ENUM('HOTSPOT', 'PPPOE', 'BOTH') NOT NULL,
    points_per_currency DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    currency_per_point DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    minimum_points_redemption INT DEFAULT 100,
    maximum_points_redemption INT,
    points_expiry_days INT DEFAULT 365,
    welcome_bonus_points INT DEFAULT 0,
    referral_bonus_points INT DEFAULT 0,
    birthday_bonus_points INT DEFAULT 0,
    anniversary_bonus_points INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    start_date TIMESTAMP NULL,
    end_date TIMESTAMP NULL,
    terms_conditions TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_name (name),
    INDEX idx_type (type),
    INDEX idx_target_service (target_service),
    INDEX idx_is_active (is_active)
);

-- Customer Loyalty table
CREATE TABLE customer_loyalty (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    loyalty_program_id BIGINT NULL,
    total_points_earned INT NOT NULL DEFAULT 0,
    total_points_redeemed INT NOT NULL DEFAULT 0,
    current_points_balance INT NOT NULL DEFAULT 0,
    total_cashback_earned DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_cashback_redeemed DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    current_cashback_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    tier_level ENUM('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND') NOT NULL DEFAULT 'BRONZE',
    tier_points_required INT,
    next_tier_points_required INT,
    last_activity_date TIMESTAMP NULL,
    points_expiry_date TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    welcome_bonus_claimed BOOLEAN DEFAULT FALSE,
    referral_count INT DEFAULT 0,
    total_referral_bonus_earned INT DEFAULT 0,
    birthday_bonus_claimed_this_year BOOLEAN DEFAULT FALSE,
    anniversary_bonus_claimed_this_year BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (loyalty_program_id) REFERENCES loyalty_programs(id),
    INDEX idx_user_id (user_id),
    INDEX idx_tier_level (tier_level),
    INDEX idx_is_active (is_active)
);

-- Configuration Scripts table
CREATE TABLE configuration_scripts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    script_content TEXT NOT NULL,
    script_type ENUM('CONFIGURATION', 'MAINTENANCE', 'MONITORING', 'SECURITY', 'BACKUP', 'RESTORE', 'USER_MANAGEMENT', 'BANDWIDTH_CONTROL', 'FIREWALL', 'QOS', 'VPN') NOT NULL,
    target_router_type ENUM('MIKROTIK', 'CISCO', 'TP_LINK', 'D_LINK', 'GENERIC', 'ALL') NOT NULL,
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    status ENUM('DRAFT', 'TESTING', 'ACTIVE', 'DEPRECATED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    is_active BOOLEAN DEFAULT TRUE,
    execution_timeout_seconds INT DEFAULT 300,
    requires_confirmation BOOLEAN DEFAULT FALSE,
    backup_before_execution BOOLEAN DEFAULT TRUE,
    rollback_script TEXT,
    parameters_json JSON,
    last_executed_at TIMESTAMP NULL,
    execution_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    failure_count INT DEFAULT 0,
    average_execution_time_seconds DOUBLE,
    tags VARCHAR(500),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_name (name),
    INDEX idx_script_type (script_type),
    INDEX idx_target_router_type (target_router_type),
    INDEX idx_status (status),
    INDEX idx_is_active (is_active)
); 