-- Create enterprise modules for GGNetworks backend
-- This migration adds FreeRADIUS integration, data plans, voucher series, and marketing campaigns

-- FreeRADIUS Integration Tables
-- Note: These tables extend the standard FreeRADIUS schema with GGNetworks-specific fields

-- Extend radcheck table with GGNetworks fields
ALTER TABLE radius.radcheck 
ADD COLUMN user_type ENUM('PPPOE_USER', 'HOTSPOT_USER', 'ADMIN_USER', 'GUEST_USER') NULL,
ADD COLUMN nas_identifier VARCHAR(64) NULL,
ADD COLUMN location_id BIGINT NULL,
ADD COLUMN router_id BIGINT NULL,
ADD COLUMN package_id BIGINT NULL,
ADD COLUMN expires_at TIMESTAMP NULL,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN data_limit_mb BIGINT NULL,
ADD COLUMN time_limit_minutes BIGINT NULL,
ADD COLUMN session_timeout BIGINT NULL,
ADD COLUMN idle_timeout BIGINT NULL,
ADD COLUMN concurrent_use INT NULL,
ADD COLUMN mac_address VARCHAR(17) NULL,
ADD COLUMN ip_address VARCHAR(45) NULL,
ADD COLUMN vlan_id INT NULL,
ADD COLUMN rate_limit_up VARCHAR(50) NULL,
ADD COLUMN rate_limit_down VARCHAR(50) NULL,
ADD COLUMN last_login TIMESTAMP NULL,
ADD COLUMN last_logout TIMESTAMP NULL,
ADD COLUMN total_data_usage_mb BIGINT NULL,
ADD COLUMN total_time_usage_minutes BIGINT NULL,
ADD COLUMN notes TEXT NULL,
ADD INDEX idx_user_type (user_type),
ADD INDEX idx_location_id (location_id),
ADD INDEX idx_router_id (router_id),
ADD INDEX idx_package_id (package_id),
ADD INDEX idx_is_active (is_active),
ADD INDEX idx_expires_at (expires_at);

-- Extend radreply table with GGNetworks fields
ALTER TABLE radius.radreply 
ADD COLUMN user_type ENUM('PPPOE_USER', 'HOTSPOT_USER', 'ADMIN_USER', 'GUEST_USER') NULL,
ADD COLUMN nas_identifier VARCHAR(64) NULL,
ADD COLUMN location_id BIGINT NULL,
ADD COLUMN router_id BIGINT NULL,
ADD COLUMN package_id BIGINT NULL,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN priority INT DEFAULT 0,
ADD COLUMN notes TEXT NULL,
ADD INDEX idx_user_type (user_type),
ADD INDEX idx_location_id (location_id),
ADD INDEX idx_router_id (router_id),
ADD INDEX idx_package_id (package_id),
ADD INDEX idx_is_active (is_active),
ADD INDEX idx_priority (priority);

-- Extend radacct table with GGNetworks fields
ALTER TABLE radius.radacct 
ADD COLUMN location_id BIGINT NULL,
ADD COLUMN router_id BIGINT NULL,
ADD COLUMN package_id BIGINT NULL,
ADD COLUMN voucher_id BIGINT NULL,
ADD COLUMN user_type ENUM('PPPOE_USER', 'HOTSPOT_USER', 'ADMIN_USER', 'GUEST_USER') NULL,
ADD COLUMN data_usage_mb BIGINT NULL,
ADD COLUMN time_usage_minutes BIGINT NULL,
ADD COLUMN rate_limit_up VARCHAR(50) NULL,
ADD COLUMN rate_limit_down VARCHAR(50) NULL,
ADD COLUMN mac_address VARCHAR(17) NULL,
ADD COLUMN ip_address VARCHAR(45) NULL,
ADD COLUMN vlan_id INT NULL,
ADD COLUMN session_cost DECIMAL(10,2) NULL,
ADD COLUMN billing_status ENUM('PENDING', 'BILLED', 'PAID', 'CANCELLED', 'REFUNDED') DEFAULT 'PENDING',
ADD INDEX idx_location_id (location_id),
ADD INDEX idx_router_id (router_id),
ADD INDEX idx_package_id (package_id),
ADD INDEX idx_voucher_id (voucher_id),
ADD INDEX idx_user_type (user_type),
ADD INDEX idx_billing_status (billing_status);

-- Data Plans Table
CREATE TABLE data_plans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_title VARCHAR(255) NOT NULL,
    plan_code VARCHAR(50) UNIQUE,
    plan_type ENUM('HOTSPOT', 'PPPOE', 'DEDICATED', 'BUSINESS', 'RESIDENTIAL', 'PREPAID', 'POSTPAID') NOT NULL,
    service_type ENUM('INTERNET', 'VOIP', 'IPTV', 'VPN', 'CLOUD_STORAGE', 'BACKUP_SERVICE') NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    original_price DECIMAL(10,2) NULL,
    duration_days INT NULL,
    duration_hours INT NULL,
    duration_minutes INT NULL,
    data_limit_mb BIGINT NULL,
    data_limit_gb BIGINT NULL,
    is_unlimited_data BOOLEAN DEFAULT FALSE,
    upload_speed_mbps INT NULL,
    download_speed_mbps INT NULL,
    voucher_prefix VARCHAR(10) NULL,
    description TEXT NULL,
    features TEXT NULL,
    is_popular BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0,
    max_concurrent_users INT DEFAULT 1,
    session_timeout_minutes INT NULL,
    idle_timeout_minutes INT NULL,
    rate_limit_up VARCHAR(50) NULL,
    rate_limit_down VARCHAR(50) NULL,
    vlan_id INT NULL,
    nas_identifier VARCHAR(64) NULL,
    router_id BIGINT NULL,
    location_id BIGINT NULL,
    valid_from TIMESTAMP NULL,
    valid_until TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_plan_type (plan_type),
    INDEX idx_service_type (service_type),
    INDEX idx_is_active (is_active),
    INDEX idx_is_popular (is_popular),
    INDEX idx_router_id (router_id),
    INDEX idx_location_id (location_id),
    INDEX idx_valid_dates (valid_from, valid_until)
);

-- Voucher Series Table
CREATE TABLE voucher_series (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    series_name VARCHAR(255) NOT NULL,
    series_code VARCHAR(50) UNIQUE,
    description TEXT NULL,
    series_type ENUM('HOTSPOT', 'PPPOE', 'GUEST', 'PROMOTIONAL', 'BUSINESS', 'RESIDENTIAL', 'TESTING') NOT NULL,
    data_plan_id BIGINT NULL,
    location_id BIGINT NULL,
    router_id BIGINT NULL,
    voucher_prefix VARCHAR(10) NULL,
    voucher_length INT DEFAULT 8,
    quantity INT NOT NULL,
    generated_count INT DEFAULT 0,
    used_count INT DEFAULT 0,
    expired_count INT DEFAULT 0,
    price_per_voucher DECIMAL(10,2) NULL,
    total_value DECIMAL(10,2) NULL,
    duration_days INT NULL,
    duration_hours INT NULL,
    duration_minutes INT NULL,
    data_limit_mb BIGINT NULL,
    data_limit_gb BIGINT NULL,
    is_unlimited_data BOOLEAN DEFAULT FALSE,
    upload_speed_mbps INT NULL,
    download_speed_mbps INT NULL,
    usage_limit INT DEFAULT 1,
    concurrent_use INT DEFAULT 1,
    session_timeout_minutes INT NULL,
    idle_timeout_minutes INT NULL,
    rate_limit_up VARCHAR(50) NULL,
    rate_limit_down VARCHAR(50) NULL,
    vlan_id INT NULL,
    nas_identifier VARCHAR(64) NULL,
    valid_from TIMESTAMP NULL,
    valid_until TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    status ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
    is_active BOOLEAN DEFAULT TRUE,
    is_roaming_enabled BOOLEAN DEFAULT FALSE,
    allow_multiple_devices BOOLEAN DEFAULT FALSE,
    check_mac_address BOOLEAN DEFAULT TRUE,
    auto_generate BOOLEAN DEFAULT FALSE,
    batch_size INT DEFAULT 100,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (data_plan_id) REFERENCES data_plans(id),
    INDEX idx_series_type (series_type),
    INDEX idx_status (status),
    INDEX idx_is_active (is_active),
    INDEX idx_data_plan_id (data_plan_id),
    INDEX idx_location_id (location_id),
    INDEX idx_router_id (router_id),
    INDEX idx_valid_dates (valid_from, valid_until),
    INDEX idx_expires_at (expires_at)
);

-- Marketing Campaigns Table
CREATE TABLE marketing_campaigns (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    campaign_name VARCHAR(255) NOT NULL,
    campaign_code VARCHAR(50) UNIQUE,
    campaign_type ENUM('BANNER', 'VIDEO', 'POPUP', 'NOTIFICATION', 'SMS_BROADCAST', 'EMAIL_CAMPAIGN', 'SOCIAL_MEDIA', 'SEARCH_ENGINE', 'AFFILIATE', 'REFERRAL') NOT NULL,
    media_type ENUM('IMAGE', 'VIDEO', 'TEXT', 'HTML', 'SMS', 'EMAIL') NOT NULL,
    title VARCHAR(255) NULL,
    subtitle VARCHAR(255) NULL,
    description TEXT NULL,
    content TEXT NULL,
    banner_url VARCHAR(500) NULL,
    video_url VARCHAR(500) NULL,
    image_url VARCHAR(500) NULL,
    thumbnail_url VARCHAR(500) NULL,
    call_to_action VARCHAR(255) NULL,
    target_url VARCHAR(500) NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    ad_counter INT NULL,
    duration_before_skip INT NULL,
    display_duration_seconds INT NULL,
    budget DECIMAL(10,2) NULL,
    spent_amount DECIMAL(10,2) NULL,
    impression_count BIGINT DEFAULT 0,
    click_count BIGINT DEFAULT 0,
    conversion_count BIGINT DEFAULT 0,
    ctr_percentage DOUBLE NULL,
    conversion_rate DOUBLE NULL,
    target_audience ENUM('ALL_USERS', 'HOTSPOT_USERS', 'PPPOE_USERS', 'NEW_USERS', 'EXISTING_USERS', 'PREMIUM_USERS', 'BUSINESS_USERS', 'RESIDENTIAL_USERS', 'GUEST_USERS', 'LOYALTY_USERS') NULL,
    location_ids TEXT NULL,
    router_ids TEXT NULL,
    package_ids TEXT NULL,
    user_segments TEXT NULL,
    device_types TEXT NULL,
    browser_types TEXT NULL,
    os_types TEXT NULL,
    frequency_cap INT NULL,
    frequency_period_hours INT NULL,
    priority INT DEFAULT 0,
    status ENUM('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'DRAFT',
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    is_roaming_enabled BOOLEAN DEFAULT FALSE,
    show_on_login BOOLEAN DEFAULT FALSE,
    show_on_package_selection BOOLEAN DEFAULT FALSE,
    show_on_payment BOOLEAN DEFAULT FALSE,
    show_on_success BOOLEAN DEFAULT FALSE,
    sms_content TEXT NULL,
    sms_recipients TEXT NULL,
    sms_scheduled_time TIMESTAMP NULL,
    sms_sent_count INT DEFAULT 0,
    sms_delivered_count INT DEFAULT 0,
    sms_failed_count INT DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_campaign_type (campaign_type),
    INDEX idx_media_type (media_type),
    INDEX idx_status (status),
    INDEX idx_is_active (is_active),
    INDEX idx_target_audience (target_audience),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_priority (priority)
);

-- Analytics Table for Usage Tracking
CREATE TABLE analytics_usage (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    username VARCHAR(64) NULL,
    user_type ENUM('PPPOE_USER', 'HOTSPOT_USER', 'ADMIN_USER', 'GUEST_USER') NULL,
    location_id BIGINT NULL,
    router_id BIGINT NULL,
    package_id BIGINT NULL,
    voucher_id BIGINT NULL,
    session_id VARCHAR(64) NULL,
    date DATE NOT NULL,
    hour INT NULL,
    data_usage_mb BIGINT DEFAULT 0,
    time_usage_minutes BIGINT DEFAULT 0,
    session_count INT DEFAULT 0,
    unique_users INT DEFAULT 0,
    peak_hour BOOLEAN DEFAULT FALSE,
    revenue DECIMAL(10,2) DEFAULT 0.00,
    cost DECIMAL(10,2) DEFAULT 0.00,
    profit DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_date (date),
    INDEX idx_user_type (user_type),
    INDEX idx_location_id (location_id),
    INDEX idx_router_id (router_id),
    INDEX idx_package_id (package_id),
    INDEX idx_hour (hour),
    INDEX idx_peak_hour (peak_hour)
);

-- Router Management Table
CREATE TABLE router_management (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    router_name VARCHAR(255) NOT NULL,
    router_ip VARCHAR(45) NOT NULL,
    router_username VARCHAR(64) NOT NULL,
    router_password VARCHAR(255) NOT NULL,
    router_port INT DEFAULT 8728,
    router_type ENUM('MIKROTIK', 'CISCO', 'UBIQUITI', 'TP_LINK', 'OTHER') DEFAULT 'MIKROTIK',
    location_id BIGINT NULL,
    location_name VARCHAR(255) NULL,
    vlan_id INT NULL,
    subnet VARCHAR(45) NULL,
    radius_secret VARCHAR(255) NULL,
    radius_ip VARCHAR(45) NULL,
    nas_identifier VARCHAR(64) NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_primary BOOLEAN DEFAULT FALSE,
    max_users INT NULL,
    current_users INT DEFAULT 0,
    bandwidth_up VARCHAR(50) NULL,
    bandwidth_down VARCHAR(50) NULL,
    uptime BIGINT NULL,
    cpu_usage DOUBLE NULL,
    memory_usage DOUBLE NULL,
    disk_usage DOUBLE NULL,
    last_sync TIMESTAMP NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_router_ip (router_ip),
    INDEX idx_location_id (location_id),
    INDEX idx_is_active (is_active),
    INDEX idx_is_primary (is_primary),
    INDEX idx_router_type (router_type)
);

-- Configuration Settings Table
CREATE TABLE configuration_settings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(255) NOT NULL UNIQUE,
    setting_value TEXT NULL,
    setting_type ENUM('STRING', 'INTEGER', 'BOOLEAN', 'DECIMAL', 'JSON', 'TEXT') NOT NULL,
    category VARCHAR(100) NULL,
    description TEXT NULL,
    is_encrypted BOOLEAN DEFAULT FALSE,
    is_public BOOLEAN DEFAULT FALSE,
    is_editable BOOLEAN DEFAULT TRUE,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category (category),
    INDEX idx_is_public (is_public),
    INDEX idx_is_editable (is_editable)
);

-- Insert default configuration settings
INSERT INTO configuration_settings (setting_key, setting_value, setting_type, category, description) VALUES
('radius.server.host', 'localhost', 'STRING', 'RADIUS', 'FreeRADIUS server host'),
('radius.server.port', '1812', 'INTEGER', 'RADIUS', 'FreeRADIUS authentication port'),
('radius.accounting.port', '1813', 'INTEGER', 'RADIUS', 'FreeRADIUS accounting port'),
('radius.secret', 'testing123', 'STRING', 'RADIUS', 'FreeRADIUS shared secret'),
('radius.nas.identifier', 'GGNetworks-Hotspot', 'STRING', 'RADIUS', 'NAS identifier for RADIUS'),
('payment.selcom.base.url', 'https://paypoint.selcommobile.com', 'STRING', 'PAYMENT', 'SELCOM payment gateway base URL'),
('payment.selcom.merchant.id', '', 'STRING', 'PAYMENT', 'SELCOM merchant ID'),
('payment.selcom.merchant.key', '', 'STRING', 'PAYMENT', 'SELCOM merchant key'),
('sms.api.base.url', 'https://api.smsprovider.com', 'STRING', 'SMS', 'SMS gateway base URL'),
('sms.api.key', '', 'STRING', 'SMS', 'SMS API key'),
('sms.sender.id', 'GGNetworks', 'STRING', 'SMS', 'SMS sender ID'),
('voucher.code.length', '8', 'INTEGER', 'VOUCHER', 'Default voucher code length'),
('voucher.default.expiration.days', '30', 'INTEGER', 'VOUCHER', 'Default voucher expiration in days'),
('session.timeout.minutes', '60', 'INTEGER', 'SESSION', 'Default session timeout in minutes'),
('accounting.interval.seconds', '300', 'INTEGER', 'ACCOUNTING', 'RADIUS accounting interval in seconds'),
('default.upload.speed', '1024', 'INTEGER', 'BANDWIDTH', 'Default upload speed in kbps'),
('default.download.speed', '2048', 'INTEGER', 'BANDWIDTH', 'Default download speed in kbps'),
('max.concurrent.sessions', '3', 'INTEGER', 'SESSION', 'Maximum concurrent sessions per user'),
('roaming.enabled', 'true', 'BOOLEAN', 'FEATURE', 'Enable roaming across locations'),
('loyalty.enabled', 'true', 'BOOLEAN', 'FEATURE', 'Enable loyalty program'),
('marketing.enabled', 'true', 'BOOLEAN', 'FEATURE', 'Enable marketing campaigns'),
('analytics.enabled', 'true', 'BOOLEAN', 'FEATURE', 'Enable usage analytics'),
('backup.enabled', 'true', 'BOOLEAN', 'FEATURE', 'Enable automatic backups'),
('maintenance.mode', 'false', 'BOOLEAN', 'SYSTEM', 'System maintenance mode'),
('maintenance.message', 'System is under maintenance. Please try again later.', 'TEXT', 'SYSTEM', 'Maintenance mode message');

-- Insert sample data plans
INSERT INTO data_plans (plan_title, plan_code, plan_type, service_type, price, duration_days, data_limit_gb, is_unlimited_data, upload_speed_mbps, download_speed_mbps, voucher_prefix, description, is_popular, is_active) VALUES
('Short Plan', 'SHORT-001', 'HOTSPOT', 'INTERNET', 1000.00, 0, NULL, true, 1, 2, 'S', '12 hours of high-speed internet access. Perfect for quick browsing and short-term needs.', false, true),
('Daily Plan', 'DAILY-001', 'HOTSPOT', 'INTERNET', 2000.00, 1, NULL, true, 2, 4, 'D', '24 hours of unlimited high-speed internet access. Ideal for daily usage and extended browsing.', true, true),
('Weekly Plan', 'WEEKLY-001', 'HOTSPOT', 'INTERNET', 6000.00, 7, NULL, true, 4, 8, 'W', '7 days of unlimited high-speed internet access. Great value for weekly usage and multiple users.', false, true),
('Monthly Plan', 'MONTHLY-001', 'HOTSPOT', 'INTERNET', 20000.00, 30, NULL, true, 8, 16, 'M', '30 days of unlimited high-speed internet access. Best value for long-term usage and heavy internet users.', true, true),
('Business Plan', 'BUSINESS-001', 'PPPOE', 'INTERNET', 50000.00, 30, NULL, true, 16, 32, 'B', 'Business-grade internet connection with priority support and guaranteed bandwidth.', false, true),
('Residential Plan', 'RESIDENTIAL-001', 'PPPOE', 'INTERNET', 25000.00, 30, NULL, true, 8, 16, 'R', 'Residential internet connection with reliable service and good value.', false, true);

-- Insert sample voucher series
INSERT INTO voucher_series (series_name, series_code, series_type, data_plan_id, voucher_prefix, voucher_length, quantity, price_per_voucher, duration_hours, is_unlimited_data, upload_speed_mbps, download_speed_mbps, status, is_active) VALUES
('Daily Vouchers', 'DAILY-SERIES-001', 'HOTSPOT', 2, 'D', 8, 100, 2000.00, 24, true, 2, 4, 'ACTIVE', true),
('Weekly Vouchers', 'WEEKLY-SERIES-001', 'HOTSPOT', 3, 'W', 8, 50, 6000.00, 168, true, 4, 8, 'ACTIVE', true),
('Monthly Vouchers', 'MONTHLY-SERIES-001', 'HOTSPOT', 4, 'M', 8, 25, 20000.00, 720, true, 8, 16, 'ACTIVE', true),
('Guest Vouchers', 'GUEST-SERIES-001', 'GUEST', 1, 'G', 8, 200, 1000.00, 12, true, 1, 2, 'ACTIVE', true);

-- Insert sample marketing campaigns
INSERT INTO marketing_campaigns (campaign_name, campaign_code, campaign_type, media_type, title, description, banner_url, start_date, end_date, ad_counter, duration_before_skip, target_audience, status, is_active, show_on_login, show_on_package_selection) VALUES
('Welcome Banner', 'WELCOME-001', 'BANNER', 'IMAGE', 'Welcome to GGNetworks', 'Get high-speed internet access with our affordable packages', '/images/banners/welcome-banner.jpg', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 3, 5, 'ALL_USERS', 'ACTIVE', true, true, false),
('Package Promotion', 'PACKAGE-001', 'BANNER', 'IMAGE', 'Special Offers', 'Get 20% off on monthly plans this week', '/images/banners/package-promo.jpg', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 3, 'HOTSPOT_USERS', 'ACTIVE', true, false, true),
('SMS Welcome', 'SMS-WELCOME-001', 'SMS_BROADCAST', 'SMS', 'Welcome Message', 'Welcome to GGNetworks! Enjoy high-speed internet access.', NULL, NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY), NULL, NULL, 'NEW_USERS', 'ACTIVE', true, false, false); 