spring:
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ggnetworks_radius?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ggnetworks
    password: ggnetworks123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration for MySQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

  # Flyway Migration - ENABLED for MySQL
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history

# RADIUS Configuration for MySQL
radius:
  database:
    enabled: true
    auto-create-tables: true
    shared-database: true

# Backend Configuration - Production Mode
backend:
  database-enabled: true
  radius-enabled: true
  use-mock-data: false
